### ISSUE TITLE
"subutai cleanup $vlan" does not always remove p2p swarm and its interface

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/subos#393]
I created x-peer env from Hub. Later I grew it. Then I destroyed it (all from Hub, though might be not related).
After this i don't see then env and its containers neither on Hub nor on SS.
However, i still can see p2p swarm and associated network interface on both peers.

**Comment by soffokl** [comment]
@Dilshat @asanaliev does HUB send `subutai cleanup $vlan`?

**Comment by Dilshat** [comment]
@soffokl yes I saw it in karaf log

**Comment by soffokl** [comment]
@Dilshat yeah, found it, thanks. 
Trying to reproduce but all times it's removes p2p interfaces without problems.

**Comment by Dilshat** [comment]
@soffokl can it be related to p2p restoring swarms (bug in p2p)

**Comment by soffokl** [comment]
@Dilshat absolutely no.

**Comment by soffokl** [comment]
@Dilshat during cleanup we are sending stop command to p2p. 
I tested even with reboot, restore does not brings up removed interfaces.

**Comment by tzununbekov** [comment]
I remember, when Dilshat mentioned this issue for the first time I've tried to reproduce it but got no described behavior. @Dilshat if you have a host where this bug is reproducible, could you provide an access to it, looks like it is a special case

**Comment by Dilshat** [comment]
@tzununbekov next time i notice i will provide access

**Comment by tzununbekov** [comment]
https://github.com/subutai-io/p2p/issues/159

**Comment by Dilshat** [comment]
https://github.com/subutai-io/p2p/issues/160

**Comment by Dilshat** [comment]
Now this issues happens very often

**Comment by akarasulu** [comment]
@tzununbekov what's the status of this?

**Comment by tzununbekov** [comment]
@akarasulu latest changes in p2p should fix it, as Mike said, so we need to test it
@Dilshat this bug was seen only on your peers, could you help us to reproduce it again?

**Comment by Dilshat** [comment]
Fixed with last update

**Comment by Dilshat** [comment]
Seems partially fixed b/c I was able to reproduce where p2p connection is removed with stop but interface is not removed

**Comment by soffokl** [comment]
@Dilshat do you have logs from this system? Please add it, without it we can't say anything about your problem.

**Comment by Dilshat** [comment]
will try to reproduce, or close otherwise

**Comment by Dilshat** [comment]
Does not reproduce
